//	BlueprintImGuiNames - the UEVR imgui.* Lua binding name list, used to populate the
//	ImGuiFunctionName enum for the generic "ImGui Call (N Args)" escape-hatch nodes.
//
//	Mechanically generated by tools/scrape_imgui_api.py from UEVR's
//	src/mods/bindings/ImGui.cpp (`imgui["name"] = api::imgui::name;` registrations).
//	Re-run that script and replace this file whenever ImGui.cpp adds/removes bindings --
//	do not hand-edit the array below.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


#pragma once


#include <string>
#include <vector>


inline const std::vector<std::string>& imguiFunctionNames() {
	static const std::vector<std::string> names = {
		"accept_drag_drop", "accept_payload", "activate_item_by_id", "align_text_to_frame_padding", "arrow_button",
		"begin_child_window", "begin_disabled", "begin_drag_drop_source", "begin_drag_drop_target", "begin_group",
		"begin_list_box", "begin_main_menu_bar", "begin_menu", "begin_menu_bar", "begin_multi_select", "begin_popup",
		"begin_popup_context_item", "begin_popup_modal", "begin_rect", "begin_table", "begin_tooltip",
		"begin_viewport_sidebar", "begin_window", "bullet", "bullet_text", "button", "calc_item_size", "calc_item_width",
		"calc_text_size", "checkbox", "clear_active_id", "close_current_popup", "close_non_modal_popups",
		"collapsing_header", "color_edit", "color_edit3", "color_edit4", "color_edit_argb", "color_picker",
		"color_picker3", "color_picker4", "color_picker_argb", "combo", "create_imu32_color", "create_imvec4_color",
		"create_platform_window", "drag_float", "drag_float2", "drag_float3", "drag_float4", "drag_int",
		"draw_list_path_clear", "draw_list_path_line_to", "draw_list_path_stroke", "draw_scene_texture",
		"end_child_window", "end_disabled", "end_drag_drop_source", "end_drag_drop_target", "end_group", "end_list_box",
		"end_main_menu_bar", "end_menu", "end_menu_bar", "end_multi_select", "end_popup", "end_rect", "end_table",
		"end_tooltip", "end_window", "focus_item", "focus_window", "get_active_id", "get_background_draw_list",
		"get_clipboard", "get_content_region_available", "get_cursor_pos", "get_cursor_screen_pos",
		"get_cursor_start_pos", "get_default_font_size", "get_display_size", "get_foreground_draw_list",
		"get_frame_height", "get_hovered_id", "get_hovered_window_name", "get_id", "get_id_from_pos", "get_item_id",
		"get_key_index", "get_mouse", "get_scroll_max_x", "get_scroll_max_y", "get_scroll_x", "get_scroll_y",
		"get_window_draw_list", "get_window_pos", "get_window_size", "indent", "input_text", "input_text_multiline",
		"invisible_button", "is_any_item_active", "is_any_item_focused", "is_any_item_hovered",
		"is_cursor_over_ui_window", "is_item_active", "is_item_clicked", "is_item_edited", "is_item_focused",
		"is_item_hovered", "is_item_toggled_open", "is_item_toggled_selection", "is_item_visible", "is_key_down",
		"is_key_pressed", "is_key_released", "is_mouse_clicked", "is_mouse_double_clicked", "is_mouse_down",
		"is_mouse_released", "is_payload_accepted", "is_popup_open", "is_window_focused", "is_window_hovered",
		"item_add", "item_size", "label_text", "load_font", "menu_item", "new_line", "open_popup", "pop_button_repeat",
		"pop_clip_rect", "pop_font", "pop_font_size", "pop_id", "pop_item_flag", "pop_item_width", "pop_style_color",
		"pop_style_var", "progress_bar", "push_button_repeat", "push_clip_rect", "push_font", "push_font_size",
		"push_id", "push_item_flag", "push_item_width", "push_override_id", "push_style_color", "push_style_var",
		"radio_button", "render_drag_drop", "same_line", "selectable", "separator", "separator_text", "set_clipboard",
		"set_cursor_pos", "set_cursor_screen_pos", "set_drag_drop_payload", "set_item_default_focus",
		"set_next_item_allow_overlap", "set_next_item_open", "set_next_item_width", "set_next_window_dock_id",
		"set_next_window_docked", "set_next_window_pos", "set_next_window_scroll", "set_next_window_size",
		"set_scroll_from_pos_x", "set_scroll_from_pos_y", "set_scroll_here_x", "set_scroll_here_y", "set_scroll_x",
		"set_scroll_y", "set_tooltip", "show_debug_log_window", "show_demo_window", "show_font_atlas",
		"show_font_selector", "show_metrics_window", "show_stack_tool_window", "slider_float", "slider_int",
		"small_button", "spacing", "table_get_column_count", "table_get_column_flags", "table_get_column_index",
		"table_get_column_name", "table_get_row_index", "table_get_sort_specs", "table_header", "table_headers_row",
		"table_next_column", "table_next_row", "table_set_bg_color", "table_set_column_index", "table_setup_column",
		"table_setup_scroll_freeze", "text", "text_colored", "text_disabled", "text_wrapped", "tree_node",
		"tree_node_ptr_id", "tree_node_str_id", "tree_pop", "unindent", "vslider_float", "vslider_int"
	};

	return names;
}
