//	ImGui-IDE — Unreal Engine source scaffolding. See unreal_codegen.h.

#include <algorithm>
#include <cctype>
#include <system_error>

#include "unreal_codegen.h"

namespace unreal::codegen {

namespace {

// Behavioral shape of a parent (which overrides the wizard emits).
enum class Kind { Actor, Pawn, Component, Object };

Kind parentKind(const std::string& parent) {
	if (parent == "APawn" || parent == "ACharacter") {
		return Kind::Pawn; // actor overrides + SetupPlayerInputComponent
	}

	if (parent == "UActorComponent" || parent == "USceneComponent") {
		return Kind::Component;
	}

	if (!parent.empty() && parent[0] == 'A') {
		return Kind::Actor;
	}

	return Kind::Object;
}

std::string upper(std::string s) {
	std::transform(s.begin(), s.end(), s.begin(), [](unsigned char c) { return static_cast<char>(std::toupper(c)); });
	return s;
}

const ParentClass* findParent(const std::string& name) {
	for (auto& p : parentClasses()) {
		if (name == p.name) {
			return &p;
		}
	}

	return nullptr;
}

} // namespace

const std::vector<ParentClass>& parentClasses() {
	static const std::vector<ParentClass> parents = {
		{"AActor", "GameFramework/Actor.h", "An object that can be placed or spawned in the world"},
		{"APawn", "GameFramework/Pawn.h", "An actor that can be possessed and receive input"},
		{"ACharacter", "GameFramework/Character.h", "A pawn with walking movement and a capsule"},
		{"AGameModeBase", "GameFramework/GameModeBase.h", "Defines the game's rules"},
		{"APlayerController", "GameFramework/PlayerController.h", "An actor responsible for controlling a pawn"},
		{"UActorComponent", "Components/ActorComponent.h", "A reusable component that can be added to any actor"},
		{"USceneComponent", "Components/SceneComponent.h", "A component with a transform, attachable to others"},
		{"UObject", "UObject/NoExportTypes.h", "A plain engine object (no world presence)"},
		{"UBlueprintFunctionLibrary", "Kismet/BlueprintFunctionLibrary.h", "Static functions callable from Blueprint"},
	};

	return parents;
}

std::string prefixedClassName(const ClassSpec& spec) {
	char prefix = (!spec.parentClass.empty() && spec.parentClass[0] == 'A') ? 'A' : 'U';
	return std::string(1, prefix) + spec.className;
}

std::string generateClassHeader(const ClassSpec& spec) {
	const ParentClass* parent = findParent(spec.parentClass);

	if (!parent || spec.className.empty()) {
		return "";
	}

	Kind kind = parentKind(spec.parentClass);
	std::string cls = prefixedClassName(spec);
	std::string api = upper(spec.moduleName) + "_API";

	std::string out;
	out += "// " + spec.className + ".h — generated by ImGui-IDE (New UE C++ Class)\n\n";
	out += "#pragma once\n\n";
	out += "#include \"CoreMinimal.h\"\n";
	out += "#include \"" + std::string(parent->include) + "\"\n";
	out += "#include \"" + spec.className + ".generated.h\"\n\n";
	out += "UCLASS()\n";
	out += "class " + api + " " + cls + " : public " + spec.parentClass + "\n";
	out += "{\n";
	out += "\tGENERATED_BODY()\n";

	if (kind == Kind::Actor || kind == Kind::Pawn) {
		out += "\npublic:\n";
		out += "\t// Sets default values for this actor's properties\n";
		out += "\t" + cls + "();\n\n";
		out += "protected:\n";
		out += "\t// Called when the game starts or when spawned\n";
		out += "\tvirtual void BeginPlay() override;\n\n";
		out += "public:\n";
		out += "\t// Called every frame\n";
		out += "\tvirtual void Tick(float DeltaTime) override;\n";

		if (kind == Kind::Pawn) {
			out += "\n\t// Called to bind functionality to input\n";
			out += "\tvirtual void SetupPlayerInputComponent(class UInputComponent* PlayerInputComponent) override;\n";
		}

	} else if (kind == Kind::Component) {
		out += "\npublic:\n";
		out += "\t// Sets default values for this component's properties\n";
		out += "\t" + cls + "();\n\n";
		out += "protected:\n";
		out += "\t// Called when the game starts\n";
		out += "\tvirtual void BeginPlay() override;\n\n";
		out += "public:\n";
		out += "\t// Called every frame\n";
		out += "\tvirtual void TickComponent(float DeltaTime, ELevelTick TickType,\n";
		out += "\t                           FActorComponentTickFunction* ThisTickFunction) override;\n";
	}

	out += "};\n";
	return out;
}

std::string generateClassSource(const ClassSpec& spec) {
	const ParentClass* parent = findParent(spec.parentClass);

	if (!parent || spec.className.empty()) {
		return "";
	}

	Kind kind = parentKind(spec.parentClass);
	std::string cls = prefixedClassName(spec);

	std::string out;
	out += "// " + spec.className + ".cpp — generated by ImGui-IDE (New UE C++ Class)\n\n";
	out += "#include \"" + spec.className + ".h\"\n";

	if (kind == Kind::Object) {
		return out; // UObject-likes: header-only boilerplate, empty translation unit
	}

	bool component = kind == Kind::Component;
	out += "\n// Sets default values\n";
	out += cls + "::" + cls + "()\n{\n";

	if (component) {
		out += "\t// Set this component to be ticked every frame. Turn off for performance\n";
		out += "\t// if you don't need it.\n";
		out += "\tPrimaryComponentTick.bCanEverTick = true;\n";

	} else {
		out += "\t// Set this actor to call Tick() every frame. Turn off for performance\n";
		out += "\t// if you don't need it.\n";
		out += "\tPrimaryActorTick.bCanEverTick = true;\n";
	}

	out += "}\n\n";
	out += "// Called when the game starts" + std::string(component ? "" : " or when spawned") + "\n";
	out += "void " + cls + "::BeginPlay()\n{\n\tSuper::BeginPlay();\n}\n\n";

	if (component) {
		out += "// Called every frame\n";
		out += "void " + cls + "::TickComponent(float DeltaTime, ELevelTick TickType,\n";
		out += "                                FActorComponentTickFunction* ThisTickFunction)\n{\n";
		out += "\tSuper::TickComponent(DeltaTime, TickType, ThisTickFunction);\n}\n";

	} else {
		out += "// Called every frame\n";
		out += "void " + cls + "::Tick(float DeltaTime)\n{\n\tSuper::Tick(DeltaTime);\n}\n";

		if (kind == Kind::Pawn) {
			out += "\n// Called to bind functionality to input\n";
			out += "void " + cls + "::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)\n{\n";
			out += "\tSuper::SetupPlayerInputComponent(PlayerInputComponent);\n}\n";
		}
	}

	return out;
}

std::pair<std::filesystem::path, std::filesystem::path>
classFilePaths(const std::filesystem::path& moduleDir, const std::string& className) {
	std::error_code ec;
	bool split = std::filesystem::is_directory(moduleDir / "Public", ec) &&
				 std::filesystem::is_directory(moduleDir / "Private", ec);

	if (split) {
		return {moduleDir / "Public" / (className + ".h"), moduleDir / "Private" / (className + ".cpp")};
	}

	return {moduleDir / (className + ".h"), moduleDir / (className + ".cpp")};
}

std::vector<std::filesystem::path> moduleDirs(const std::filesystem::path& uproject) {
	std::vector<std::filesystem::path> modules;
	std::error_code ec;
	std::filesystem::path source = uproject.parent_path() / "Source";

	for (auto it = std::filesystem::directory_iterator(source, ec);
		 !ec && it != std::filesystem::directory_iterator(); it.increment(ec)) {
		std::error_code dec;

		if (!it->is_directory(dec) || dec) {
			continue;
		}

		// a module dir contains <Name>.Build.cs
		std::error_code fec;
		if (std::filesystem::exists(it->path() / (it->path().filename().string() + ".Build.cs"), fec)) {
			modules.push_back(it->path());
		}
	}

	std::sort(modules.begin(), modules.end());
	return modules;
}

std::string sanitizeVerseName(const std::string& raw) {
	// Verse device classes are snake_case identifiers: lowercase letters, digits and
	// underscores, not starting with a digit.
	std::string out;

	for (unsigned char c : raw) {
		if (std::isalnum(c)) {
			out += static_cast<char>(std::tolower(c));

		} else if ((c == '_' || c == ' ' || c == '-') && !out.empty() && out.back() != '_') {
			out += '_';
		}
	}

	while (!out.empty() && out.back() == '_') {
		out.pop_back();
	}

	if (!out.empty() && std::isdigit(static_cast<unsigned char>(out[0]))) {
		out = "device_" + out;
	}

	return out.empty() ? "my_device" : out;
}

std::string generateVerseDevice(const std::string& deviceName) {
	std::string name = sanitizeVerseName(deviceName);

	std::string out;
	out += "# " + name + ".verse — generated by ImGui-IDE (New Verse Device)\n";
	out += "\n";
	out += "using { /Fortnite.com/Devices }\n";
	out += "using { /Verse.org/Simulation }\n";
	out += "using { /UnrealEngine.com/Temporary/Diagnostics }\n";
	out += "\n";
	out += "# A Verse-authored creative device that can be placed in a level\n";
	out += name + " := class(creative_device):\n";
	out += "\n";
	out += "    # Runs when the device is started in a running game\n";
	out += "    OnBegin<override>()<suspends>:void=\n";
	out += "        Print(\"Hello from " + name + "!\")\n";
	return out;
}

} // namespace unreal::codegen
