#!/usr/bin/env python3
"""
scrape_imgui_api.py - regenerate BlueprintImGuiNames.h from UEVR's ImGui.cpp.

UEVR's src/mods/bindings/ImGui.cpp registers its Lua imgui table as a flat list of
    imgui["name"] = api::imgui::name;
assignments. This script extracts every registered name and rewrites
BlueprintImGuiNames.h's array so the Blueprint editor's "ImGui Call (N Args)"
escape-hatch nodes' function picker always matches the real binding surface.

Usage:
    python tools/scrape_imgui_api.py --uevr-root <path-to-UEVR-checkout>

Re-run this whenever ImGui.cpp gains or loses bindings; the output is a normal source
file -- review the diff and commit it like any other generated artifact.
"""

import argparse
import re
import sys
from pathlib import Path

BINDING_PATTERN = re.compile(r'\w+\["([a-z_0-9]+)"\]\s*=\s*api::imgui::')

HEADER_TEMPLATE = '''//	BlueprintImGuiNames - the UEVR imgui.* Lua binding name list, used to populate the
//	ImGuiFunctionName enum for the generic "ImGui Call (N Args)" escape-hatch nodes.
//
//	Mechanically generated by tools/scrape_imgui_api.py from UEVR's
//	src/mods/bindings/ImGui.cpp (`imgui["name"] = api::imgui::name;` registrations).
//	Re-run that script and replace this file whenever ImGui.cpp adds/removes bindings --
//	do not hand-edit the array below.
//
//	This work is licensed under the terms of the MIT license.
//	For a copy, see <https://opensource.org/licenses/MIT>.


#pragma once


#include <string>
#include <vector>


inline const std::vector<std::string>& imguiFunctionNames() {{
	static const std::vector<std::string> names = {{
{body}
	}};

	return names;
}}
'''


def scrape(imgui_cpp: Path) -> list[str]:
    text = imgui_cpp.read_text(encoding="utf-8", errors="ignore")
    names = sorted(set(BINDING_PATTERN.findall(text)))
    if not names:
        sys.exit(f'no imgui["..."] bindings found in {imgui_cpp} -- did the file move or the pattern change?')
    return names


def format_body(names: list[str]) -> str:
    lines = []
    line = "\t\t"
    for name in names:
        token = f'"{name}", '
        if len(line) + len(token) > 116:
            lines.append(line.rstrip())
            line = "\t\t"
        line += token
    if line.strip():
        lines.append(line.rstrip().rstrip(","))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--uevr-root", required=True, type=Path, help="path to a UEVR checkout")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "BlueprintImGuiNames.h",
        help="output header path (default: BlueprintImGuiNames.h next to BlueprintLua.cpp)",
    )
    args = parser.parse_args()

    imgui_cpp = args.uevr_root / "src" / "mods" / "bindings" / "ImGui.cpp"
    if not imgui_cpp.is_file():
        sys.exit(f"not found: {imgui_cpp} -- pass --uevr-root <path-to-UEVR-checkout>")

    names = scrape(imgui_cpp)
    args.out.write_text(HEADER_TEMPLATE.format(body=format_body(names)), encoding="utf-8")
    print(f"wrote {len(names)} names to {args.out}")


if __name__ == "__main__":
    main()
